blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns=[
        path('category/', views.category, name='category'),
        path('test/', views.test, name='test'),
        path('', views.post_list, name='post_list'),
        path('contact.html', views.contact, name='contact'),
        # path('', views.PostListView.as_view(), name='post_list'),
        path('tag/<slug:tag_slug>', views.tagss, name='post_list_by_tag'),
        path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
        path('<int:post_id>/share/', views.post_share, name='post_share'),
        path('feed/', LatestPostFeed(), name='post_feed'),
        path('blog_search', views.blog_search, name='blog-search'),
    ]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

sitemaps = {'posts':PostSitemap,}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    # path('', include('users.urls'),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')), 
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.conf import settings

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES= ( ('draft','Draft'),('published','Published'),
                      )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='blog_posts')
    body = models.TextField()
    image = models.ImageField(blank=True, null=True)
    # hello = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                    args=[self.publish.year,
                          self.publish.month,
                          self.publish.day,
                          self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from django.forms import widgets
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TextInput(attrs={
        'type':"text",
        'class':"form-control mr-3",
        'placeholder':"Add comment",
    }), label='')

    class Meta:
        model = Comment
        fields = ('body',)

# class SearchForm(forms.Form):
#     query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger 
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from urllib.parse import quote_plus
from django.core.mail import send_mail

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

def post_list(request, tag_slug=None):
    object_list = Post.published.all()

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])


    paginator = Paginator(object_list,7)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    losts = posts[:3]
    this_urls = request.get_full_path
    if len(str(this_urls)) == 66:
        this_url= 'lol'
    else:
        this_url = False
        
    if request.method == 'POST':
        message_name = request.POST['message-name']
        message_lname = request.POST['message-lname']
        message_email = request.POST['message-email']
        message = request.POST['message']

    #send mail
        send_mail(
            'message from ' + message_name + ' ' + message_lname + ' their email ' + message_email ,
            message, 
            message_email, 
            ['pmasuper34@gmail.com'],
        )


        return render(request, 'blog/post/list.html', {'page':page, 'posts':posts, 'tag':tag, 'message_name':message_name, 'losts':losts, 'this_url':this_url, 'this_urls':this_urls})
    else:
        return render(request, 'blog/post/list.html', {'page':page, 'posts':posts, 'tag':tag, 'losts':losts, 'this_url':this_url, 'this_urls':this_urls})
    
    


def post_detail(request, year, month, day, post):

    post = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year, publish__month=month,
                             publish__day=day)
    
    share_string = quote_plus(post.title)

    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method =='POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
        
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

    post_image = post.image

    this_url = request.get_full_path

    return render(request, 'blog/post/detail.html', {'post':post, 'comments':comments, 'new_comment':new_comment, 'comment_form':comment_form, 'similar_posts':similar_posts, 'share_string':share_string, 'post_image':post_image, 'this_url':this_url})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} recommends you read' f'{post.title}'
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'pmasuper34@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def blog_search(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        posts = Post.objects.filter(title__contains=searched)
        
        

        return render(request, 'blog/blog_search.html', {'searched':searched, 'posts':posts})
    else:
        return render(request, 'blog/blog_search.html', {})

def contact(request):
    if request.method == 'POST':
        message_name = request.POST['message-name']
        message_lname = request.POST['message-lname']
        message_email = request.POST['message-email']
        message = request.POST['message']

        #send mail
        send_mail(
            'message from ' + message_name + ' ' + message_lname + ' their email ' + message_email ,
            message, 
            message_email, 
            ['pmasuper34@gmail.com'],
        )

        return render(request, 'blog/contact.html', {'message_name':message_name})
    else:
        return render(request, 'blog/contact.html', {})


def test(request, tag_slug=None):
    first_post = Post.objects.get()
    object_list = Post.published.all()

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    return render(request, 'blog/test.html', {'first_post':first_post, 'tag':tag})


def tagss(request, tag_slug=None):
    object_list = Post.published.all()

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])


    paginator = Paginator(object_list,7)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if request.method == 'POST':
        message_name = request.POST['message-name']
        message_lname = request.POST['message-lname']
        message_email = request.POST['message-email']
        message = request.POST['message']

    #send mail
        send_mail(
            'message from ' + message_name + ' ' + message_lname + ' their email ' + message_email ,
            message, 
            message_email, 
            ['pmasuper34@gmail.com'],
        )

        return render(request, 'blog/tags.html', {'page':page, 'posts':posts, 'tag':tag, 'message_name':message_name})
    else:
        return render(request, 'blog/tags.html', {'page':page, 'posts':posts, 'tag':tag})


def category(request, tag_slug=None):
    object_list = Post.published.all()

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])


    paginator = Paginator(object_list,7)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    losts = posts[:3]

    if request.method == 'POST':
        message_name = request.POST['message-name']
        message_lname = request.POST['message-lname']
        message_email = request.POST['message-email']
        message = request.POST['message']

    #send mail
        send_mail(
            'message from ' + message_name + ' ' + message_lname + ' their email ' + message_email ,
            message, 
            message_email, 
            ['pmasuper34@gmail.com'],
        )

        return render(request, 'blog/category.html', {'page':page, 'posts':posts, 'tag':tag, 'message_name':message_name, 'losts':losts})
    else:
        return render(request, 'blog/category.html', {'page':page, 'posts':posts, 'tag':tag, 'losts':losts})
    
    

blog/templates/blog/base_copy.html
{% load blog_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css1/blog.css' %}" rel="stylesheet"> 
        <link href="{% static 'css1/style.css' %}" rel="stylesheet"> 
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        

        <style>
.button {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 8px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  transition-duration: 0.4s;
  cursor: pointer;
}

.button1 {
  background-color: white; 
  color: black; 
  border: 2px solid #4CAF50;
}

.button1:hover {
  background-color: #4CAF50;
  color: white;
}

</style>


    </head>
    <body>

        <div class="navbar">
            <a href="/">Home</a>
            <a href="/contact.html">Contact</a>
            <div class="dropdown">
              <button class="dropbtn">Dropdown
                <i class="fa fa-caret-down"></i>
              </button>
              <div class="dropdown-content">
                <a href="#">Link 1</a>
                <a href="#">Link 2</a>
                <a href="#">Link 3</a>
              </div>
            </div>
          </div>
        <div id='content'>

<script>
/* When the user clicks on the button, 
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(e) {
    if (!e.target.matches('.dropbtn')) {
    var myDropdown = document.getElementById("myDropdown");
    if (myDropdown.classList.contains('show')) {
        myDropdown.classList.remove('show');
    }
    }
}
</script>

<script async defer src="https://assets.pinterest.com/js/pinit.js"></script>
            {% block content %}
            {% endblock %}
        
        </div>
        <div id='sidebar'>
            <h2>Shrek's Swamp</h2>
            <p>This is where you'll write shit about your blog like what is it about and what can people find here etc etc. or write whatever you want idc. Just remember that it's gonna be displayed on every single page you visit.
             I'm just writing this to fill the gap so that i can see how stuff looks.. so don't even bother reading this. Well ig it's too late for that now. <br><br>Also dont click on this <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">link</a> a</p>
             <p>I've written {% total_posts %} blogs so far...</p>
             <p>
                <a href="{% url 'blog:post_feed' %}">This is my RSS feed</a>
            </p>
             <h3>Latest Posts</h3>
             {% show_latest_posts 3 %}

             <h3>Most Commented Posts</h3>
             {% get_most_commented_post as most_commented_posts %}
             <ul>
                 {% for post in most_commented_posts %}
                 <li>
                     <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                 </li>
                 {% endfor %}
             </ul>
        </div>

    </body>
</html>

blog/templates/blog/basem2.html
{% load blog_tags %}
{% load static %}


<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'menu2/fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'menu2/css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'menu2/css/bootstrap.min.css' %}">
    
    <!-- Style -->
    <link rel="stylesheet" href="{% static 'menu2/css/style.css' %}">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>


    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
   
    
    <header class="site-navbar js-sticky-header site-navbar-target" role="banner">

      <div class="container">
        <div class="row align-items-center">
          
          <div class="col-6 col-xl-2">
            <h1 class="mb-0 site-logo"><a href="/">BLOG NAME<span class="text-primary">.</span> </a></h1>
          </div>

          <div class="col-12 col-md-10 d-none d-xl-block">
            <nav class="site-navigation position-relative text-right" role="navigation">

              <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                <li><a href="/" class="nav-link">Home</a></li>
                <li class="has-children">
                  <a href="#about-section" class="nav-link">About Us</a>
                  <ul class="dropdown">
                    <li><a href="#team-section" class="nav-link">Team</a></li>
                    <li><a href="#pricing-section" class="nav-link">Pricing</a></li>
                    <li><a href="#faq-section" class="nav-link">FAQ</a></li>
                    <li><a href="#gallery-section" class="nav-link">Gallery</a></li>
                    <li><a href="#services-section" class="nav-link">Services</a></li>
                    <li><a href="#testimonials-section" class="nav-link">Testimonials</a></li>
                    <li class="has-children">
                      <a href="#">More Links</a>
                      <ul class="dropdown">
                        <li><a href="#">Menu One</a></li>
                        <li><a href="#">Menu Two</a></li>
                        <li><a href="#">Menu Three</a></li>
                      </ul>
                    </li>
                  </ul>
                </li>
                
                
                <li><a href="#blog-section" class="nav-link">Blog</a></li>
                <li><a href="/contact.html" class="nav-link">Contact</a></li>
                <li class="social"><a href="http://www.facebook.com" class="nav-link"><span class="icon-facebook"></span></a></li>
                <li class="social"><a href="http://www.twitter.com" class="nav-link"><span class="icon-twitter"></span></a></li>
                <li class="social"><a href="http://www.linkedin.com" class="nav-link"><span class="icon-linkedin"></span></a></li>
              </ul>
            </nav>
          </div>


          <div class="col-6 d-inline-block d-xl-none ml-md-0 py-3" style="position: relative; top: 3px;"><a href="#" class="site-menu-toggle js-menu-toggle float-right"><span class="icon-menu h3"></span></a></div>

        </div>
      </div>
      
    </header>

    <div class="hero">
        <img src="media/hero_3.jpg" alt="some random picture" style="height:680px;width:100%" usemap="#workmap">

<map name="workmap">
  <area shape="rect" coords="0,0,1800,680" alt="Computer" href="#">

    </div>

 

    {% block content %}
    {% endblock %}

    
    

    <script src="{% static 'menu2/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'menu2/js/popper.min.js' %}"></script>
    <script src="{% static 'menu2/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'menu2/js/jquery.sticky.js' %}"></script>
    <script src="{% static 'menu2/js/main.js' %}"></script>

 
  </body>
</html>

blog/templates/blog/blog_search.html
{% extends 'blog/base.html' %}
{% load static %}

 
{% block content %}

    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    

    <!-- Bootstrap core CSS -->
    <link href="{% static 'search_result/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'search_result/assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'search_result/assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'search_result/assets/css/owl.css' %}">
<img src="media/search2.png" width=100% height=auto>

    {% if searched %}
    <center>
          <br><br>
    <h1> You searched for "{{ searched }}"</h1>
      </center>
    
<br><br>
    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
 
            {% for post in posts %}
                <div class="col-lg-6">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="{{ post.image.url }}" alt="">
                    </div>
                    <div class="down-content">
                      <a href="{{ post.get_absolute_url }}"><h4>{{ post.title}}</h4></a>
                      
                      <p> {{ post.body| truncatewords:10 }}</p>

                      <ul class="post-info">
                        <li><a href="#">{{ post.author }}</a></li>
                        <li><a href="#">{{ post.publish }}</a></li>                      </ul>
                    </div>
                  </div>
                </div>
          

                {% endfor %}
                {% else %}
                <div class="container-b">
                    <div class="bottom-right-b">
                        
                  <h1>Oops! You didn't write anything...</h1>
                    </div>
                    </div>
                {% endif %}
               
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'search_result/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'search_result/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'search_result/assets/js/custom.js' %}"></script>
    <script src="{% static 'search_result/assets/js/owl.js' %}"></script>
    <script src="{% static 'search_result/assets/js/slick.js' %}"></script>
    <script src="{% static 'search_result/assets/js/isotope.js' %}"></script>
    <script src="{% static 'search_result/assets/js/accordions.js' %}"></script>

    <script language = "{ % static 'search_result/text/Javascript' %}"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>



{% endblock %}

blog/templates/blog/contact.html
<br/>
{% if message_name %}
<h1>{{ message_name }} Your message has been submitted. We will get back to you soon..</h1>
{% else %}
<form action="#" method="POST" id="myNiceForm">
    {% csrf_token %}
    <input type="text" name='message-name' placeholder="Your Name"><br><br>
    <input type="text" name='message-lname' placeholder="Your Name"><br><br>
    <input type="email" name='message-email' placeholder="Your Email"><br><br>
    <textarea name='message' placeholder="Your Message"></textarea>
   <br/><br/><br/>
    <button type="submit">Send Message</button>
    <br><br><br>
</form>

{% endif %}

blog/templates/blog/footer.html
{% load static %}


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'footer/css/style.css' %}">
</head>

<body>
    <div class="footer-basic">
        <footer>
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Subscribe</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Books</a></li>
                <li class="list-inline-item"><a href="#">Categories</a></li>
            </ul>
            <p class="copyright">Blog Name and Copyrights etc © 2021</p>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</body>

blog/templates/blog/searchbarform.html
<li>
    <form method='POST' action="blog_search">
        {% csrf_token %}
        <input type='search' placeholder="search post" aria-label="Search" name="searched">
       
       <i class="fa fa-search"></i>
      </form>
      <p></p>
</li>


<style>
    form{
        position: relative;
    
        left: 50%;
        transform: translate(-50%,90%);
        transition: all 1s;
        width: 25px;
        height: 25px;
        background: rgb(255, 255, 255);
        box-sizing: border-box;
        border-radius: 25px;
        border: 4px solid white;
        padding: 3px;
    }
    
    input{
        position: absolute;
        transform: translate(0%,0%);
        top: 0;
        left: 0;
        width: 100%;;
        height: 15.5px;
        line-height: 30px;
        outline: 0;
        border: 0;
        display: none;
        font-size: 1em;
        border-radius: 20px;
        padding: 0 20px;
    }
    
    .fa{
        transform: translate(30%,-18%);
        box-sizing: border-box;
        padding: 5px;
        width: 30.5px;
        height: 30.5px;
        position: absolute;
        top: 0;
        right: 0;
        border-radius: 50%;
        color: #07051a;
        text-align: center;
        font-size: 1.2em;
        transition: all 1s;
    }
    
    form:hover{
        width: 200px;
        cursor: pointer;
    }
    
    form:hover input{
        display: block;
    }
    
    form:hover .fa{
        background: #07051a;
        color: white;
    } 
    
    </style>
    
    <br>
    <p>HELLO</p>
    <form method='POST' action="blog_search">
      {% csrf_token %}
      <input type='search' placeholder="search post" aria-label="Search" name="searched">
     
     <i class="fa fa-search"></i>
    </form>
    

blog/templates/blog/tags.html
{% extends 'blog/base.html' %}
{% load static %}
{% load blog_tags %}




{% block content %}



{% load static %}
{% load blog_tags %}
<head>
<link href="{% static 'lists/layout/styles/layout.css' %}" rel="stylesheet" type="text/css" media="all">
</head>
<br><br><br><br>
<body id="top">
    <div class="sectiontitle">
      <h6 class="heading">Posts related to {{ tag.name}}.</h6>
      <p>Here are all the posts written so far.</p>
    </div>
    <div class="wrapper row2">
        <section id="latest" class="hoc container clear"> 
    <!-- ################################################################################################ -->
  
    <ul class="nospace group">
        {% for post in posts %}

        <li class="one_third">
            <article>
              <figure><a href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }}" alt=""></a>
                <figcaption>
                  <p>{{post.publish}}
                </figcaption>
              </figure>
              <div class="excerpt">
                <h6 class="heading">{{ post.title }}</h6>
                <ul class="nospace meta">
               
                  <li><i class="fas fa-user"></i> <a href="#">{{ post.author}}</a></li>
                  
                  <li><i class="fas fa-tags"></i> {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %} {% endfor %}</li>
    
               
                </ul>
                {{ post.body| truncatewords:10 }}
                <br><br>
                <footer><a class="btn" href="{{ post.get_absolute_url }}">Read More</a></footer>
              </div>
            </article>   
          </li>
          {% endfor %}
        
        

    </ul>
</section>
</div>
</body>


<a id="backtotop" href="#top"><i class="fas fa-chevron-up"></i></a>
<!-- JAVASCRIPTS -->
<script src="{% static 'lists/layout/scripts/jquery.min.js' %}"></script>
<script src="{% static 'lists/layout/scripts/jquery.backtotop.js' %}"></script>
<script src="{% static 'lists/layout/scripts/jquery.mobilemenu.js' %}"></script>
<br><br><br><br><br><br><br>
{% include 'blog/footer.html' %}

{% endblock %}